version: "3"

services:
  postgres:
    image: postgres:latest
    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "${POSTGRES_PORT}:5432"
    networks:
      - appnetwork

volumes:
  postgre_data:

networks:
  appnetwork:
    driver: bridge